### PR TITLE
Use HTTP rather than ASCII whitespace

### LINKED ISSUE #89: MIME type parsing: stop treating 0x0C as whitespace
See https://github.com/whatwg/fetch/pull/818#pullrequestreview-166582578 for context.

### PR DESCRIPTION
**Pull request by annevk**
Tests: https://github.com/web-platform-tests/wpt/pull/13615.

Fixes #89.

***
<a href="https://whatpr.org/mimesniff/90.html" title="Last updated on Oct 30, 2018, 1:11 PM GMT (7a80894)">Preview</a> | <a href="https://whatpr.org/mimesniff/90/dc35803...7a80894.html" title="Last updated on Oct 30, 2018, 1:11 PM GMT (7a80894)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
(The reason Travis fails is because HTTP whitespace isn't yet defined by Fetch.)

**Comment by annevk** [comment]
Hmm, so I guess I should look into contexts where MIME types can have newlines and how those are handled today (or not handled at all).

**Comment by annevk** [comment]
Per https://github.com/whatwg/mimesniff/issues/42#issuecomment-346104195 `canPlayType()` et al, `overrideMimeType()`, and `Blob` look like the places where newlines could show up.

Because of that I think we should use HTTP whitespace here and not HTTP tab or space. Implementations that don't share their MIME type parser across the code base could have slightly more restrictive code in contexts where newlines by definitions cannot show up.

@MattMenke2 @asankah I take it that's agreeable? (I'll add some tests for the aforementioned contexts as well if they don't have any for newlines.)

Note to self: need to add HTTP whitespace (a code point based version) to Fetch.

**Comment by MattMenke2** [comment]
Is this just CRs and LFs?  If so, I'm fine with that.

**Comment by annevk** [comment]
Yes.

**Comment by annevk** [comment]
I updated the tests to also test HTTP newlines (as per above) and created https://github.com/whatwg/fetch/pull/828 to define HTTP whitespace in Fetch for this kind of usage (and added a note that hopefully dissuades others from using it unless they have an eerily similar data structure).

**Pull request merged**
