### PR TITLE
Reference ENCODING for the definition of operators, and define ~.

### PR DESCRIPTION
**Pull request by padenot**

### CODE REVIEW

**Comment by annevk** [comment]
You patched the wrong file here. Needs to be in Overview.src.html.

**Comment by padenot** [comment]
Oops yes, rebased and fixed.

**Comment by annevk** [comment]
It seems like you need an updated version of xref. But I can pull this in and regenerate.

**Comment by padenot** [comment]
Thanks, I had forgotten to `git add` before `git commit --amend`. I also put in a `<span>` instead of the `[ ]` notation.

**Comment by annevk** [comment]
I gave you write access to the repository so you can create branches directly on this repository for PRs in the future.

**Pull request merged**
